### ISSUE TITLE
Error using with Cloud version

### ISSUE THREAD

**Issue by rtcms** [jc1518/Confluence-Space-Exporter#11]
Hey,
I get this error while using with Cloud Deployment of Confluence
```
401 - "Basic authentication with passwords is deprecated.  For more information, see: https://developer.atlassian.com/cloud/confluence/deprecation-notice-basic-auth/\n"
```
Am I missing anything?

**Comment by jc1518** [comment]
As the error says Confluence cloud does not allow basic authentication. The tool was created for Server version.

**Comment by jc1518** [comment]
As the error says Confluence cloud does not allow basic authentication. The tool was created for Server version.
